### ISSUE TITLE
Can not run project

### ISSUE THREAD

**Issue by manhcuongbk56** [AKSW/cubeqa#35]
Hello
I was trying to run your project and i got this problem: 
"Failed to execute goal on project cubeqa: Could not resolve dependencies for project org.aksw.cubeqa:cubeqa:jar:0.0.1-SNAPSHOT: Could not find artifact org.aksw:openspending2rdf:jar:0.0.1-SNAPSHOT in maven.aksw.internal (http://maven.aksw.org/repository/internal) -> [Help 1]"
I don't know how to fix it. Can you help me to resolve it? I'm just a student coming from Viet Nam, so if i take a mistake in this comment, please forgive me, thank you.

**Comment by KonradHoeffner** [comment]
Sorry for the late answer. Can you try it again? Our Maven repository may have had technical issues in October.

**Comment by manhcuongbk56** [comment]
Thank for your answer. I tried so many ways to run project but nothing works. So i gave it up to move on to another project. I'll try it again when i'm free, thank for your support.

**Comment by KonradHoeffner** [comment]
I just cloned a fresh copy on a second machine with an empty maven repository and "mvn compile" ran without issue, so I am closing this for now. If this problem reappears please open a new issue.
